// <auto-generated />
namespace ProjetoIntegrador_Subway.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterandovalorProdutoparatypeNumeric : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterandovalorProdutoparatypeNumeric));
        
        string IMigrationMetadata.Id
        {
            get { return "201805241150064_Alterando valorProduto para type Numeric"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
