// <auto-generated />
namespace ProjetoIntegrador_Subway.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RemovendototalQtddaPedido_Ingredientes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovendototalQtddaPedido_Ingredientes));
        
        string IMigrationMetadata.Id
        {
            get { return "201806190225210_Removendo totalQtd da Pedido_Ingredientes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
