// <auto-generated />
namespace ProjetoIntegrador_Subway.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AdicionandoocampopgtRecebidonatabelaProdutos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicionandoocampopgtRecebidonatabelaProdutos));
        
        string IMigrationMetadata.Id
        {
            get { return "201805241248079_Adicionando o campo pgtRecebido na tabela Produtos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
